export { default as AddProductsPage } from "./AddProductsPage";
export { default as BrandsPage } from "./BrandsPage";
export { default as CategoriesPage } from "./CategoriesPage";
export { default as HomePage } from "./HomePage";
export { default as LoginPage } from "./LoginPage";
export { default as NotFoundPage } from "./NotFoundPage";
export { default as ProductPage } from "./ProductPage";
export { default as SearchPage } from "./SearchPage";
export { default as SignupPage } from "./SignupPage";